version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: inzynierka_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=InzynierkaDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: inzynierka_backend
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=InzynierkaDb;User Id=postgres;Password=test;
      - Jwt__Key=DLUGIKLUCZJWT!@#$^%&^*()#@*($@#*(%$@*)#@#)(!)#*(%$@(*%(#$)@$*)@#)(*%$@#)(*%$@#)(*%$@#)
      - Jwt__Issuer=http://localhost:8080
      - Jwt__Audience=http://localhost:8080
      - FrontendUrl=http://localhost:3000
      - USE_HTTPS_REDIRECTION=false
    depends_on:
      - db

  frontend:
    container_name: inzynierka_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: