name: CI Pipeline (Build & Test)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test-backend:
    name:  Backend Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore backend/backend/backend.csproj

      - name: Build Backend
        run: dotnet build backend/backend/backend.csproj --no-restore --configuration Release

      - name:  Run Unit Tests
        run: dotnet test backend/backend/backend.Tests/backend.Tests.csproj --no-build --verbosity normal

  build-frontend:
    name:  Frontend Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        env:
          VITE_API_URL: "http://localhost:8080/api"
        run: npm run build